# Generated by Django 5.0.7 on 2024-07-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dht_humidity', models.FloatField(blank=True)),
                ('dht_temperature', models.FloatField(blank=True)),
                ('soil_moisture', models.FloatField(blank=True)),
                ('rain', models.FloatField(blank=True)),
                ('light', models.FloatField(blank=True)),
                ('analog_temperature', models.FloatField(blank=True)),
                ('digital_temperature', models.FloatField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
