# Generated by Django 5.0.7 on 2024-07-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_sensordata_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='timestamp',
            field=models.DateTimeField(default='2024-07-26 14:07:00'),
        ),
    ]
